label: Author Agent

# Admin
admin: [0.0.0.0, 3005]
admin-insecure-mode: true

# Transport
inbound-transport:
  - [http, 0.0.0.0, 3003]
  - [ws, 0.0.0.0, 3004]
outbound-transport: http
endpoint:
  - http://author-agent:3003
  - ws://author-agent:3004

# Ledger
# Indicio TestNet
genesis-url: https://raw.githubusercontent.com/indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
# Sovrin BuilderNet
# genesis-url: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true

# Credentials and Presentations
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true

auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

# Revocation Registry
tails-server-base-url: http://tails-server:6543
notify-revocation: true
monitor-revocation-notification: true

# Wallet
wallet-name: author_wallet
wallet-type: indy
wallet-key: "insecure, for use in testing only"
auto-provision: true
wallet-storage-type: postgres_storage
wallet-storage-config: '{"url":"db:5432","wallet_scheme":"MultiWalletSingleTable","max_connections":5}'
wallet-storage-creds: '{"account":"acapy","password":"acapy","admin_account":"acapy","admin_password":"acapy"}'


# Multitenancy
multitenant: true
multitenant-admin: true

# Author
auto-request-endorsement: true
auto-write-transactions: true
auto-create-revocation-transactions: true
endorser-protocol-role: author
endorser-alias: endorser
public-invites: true

# Log
log-level: error

# Create default invitation to populate wallet
invite-label: Author (Admin)
connections-invite: true
invite-metadata-json: '{"group": "admin"}'